[package]
name = "libcontainer"
version = "0.0.4"
description = "Library for container control"
license-file = "../../LICENSE"
repository = "https://github.com/containers/youki"
homepage = "https://containers.github.io/youki"
readme = "README.md"
authors = ["youki team"]
edition = "2021"
rust-version = "1.58.1"
keywords = ["youki", "container", "cgroups"]

[features]
default = ["systemd", "v2", "v1"]
systemd = ["libcgroups/systemd", "v2"]
v2 = ["libcgroups/v2"]
v1 = ["libcgroups/v1"]
cgroupsv2_devices = ["libcgroups/cgroupsv2_devices"]

[dependencies]
anyhow = "1.0"
bitflags = "2.0.1"
caps = "0.5.5"
chrono = { version = "0.4", features = ["serde"] }
crossbeam-channel = "0.5"
fastrand = "^1.7.0"
futures = { version = "0.3", features = ["thread-pool"] }
libc = "0.2.140"
log = "0.4"
mio = { version = "0.8.6", features = ["os-ext", "os-poll"] }
nix = "0.26.2"
path-clean = "1.0.1"
oci-spec = { version = "^0.6.0", features = ["runtime"] }
procfs = "0.15.1"
prctl = "1.0.0"
libcgroups = { version = "0.0.4", path = "../libcgroups", default-features = false }
libseccomp = { version = "0.3.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syscalls = "0.6.7"
rust-criu = "0.4.0"
clone3 = "0.2.3"

[dev-dependencies]
oci-spec = { version = "^0.6.0", features = ["proptests", "runtime"] }
quickcheck = "1"
serial_test = "1.0.0"
rand = "0.8.5"
