[package]
name = "libcontainer"
version = "0.0.1"
authors = ["youki team"]
edition = "2021"
description = "Library for container creation"

[dependencies]
anyhow = "1.0"
caps = "0.5.3"

chrono = { version="0.4", features = ["serde"] }
crossbeam-channel = "0.5"
dbus = "0.9.5"
fastrand = "1.4.1"
futures = { version = "0.3", features = ["thread-pool"] }
libc = "0.2.108"
log = "0.4"
mio = { version = "0.8.0", features = ["os-ext", "os-poll"] }
nix = "0.23.0"
oci-spec = { git = "https://github.com/containers/oci-spec-rs",  rev = "54c5e386f01ab37c9305cc4a83404eb157e42440" }
path-clean = "0.1.0"
procfs = "0.11.0"
prctl = "1.0.0"
libcgroups = { version = "0.1.0", path = "../libcgroups" }
libseccomp = { version = "0.1.0", path = "../libseccomp" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
oci-spec = { git = "https://github.com/containers/oci-spec-rs",  rev = "54c5e386f01ab37c9305cc4a83404eb157e42440", features = ["proptests"] }
quickcheck = "1"
serial_test = "0.5.1"