[package]
name = "libcontainer"
version = "0.0.3"
description = "Library for container control"
license-file = "../../LICENSE"
documentation = "https://docs.rs/libcontainer"
repository = "https://github.com/containers/youki"
homepage = "https://containers.github.io/youki"
readme = "README.md"
authors = ["youki team"]
edition = "2021"
rust-version = "1.58.1"
keywords = ["youki", "container", "cgroups"]

[features]
default = []
wasm-wasmer = ["wasmer", "wasmer-wasi"]

[dependencies]
anyhow = "1.0"
bitflags = "1.3.2"
caps = "0.5.3"
chrono = { version="0.4", features = ["serde"] }
crossbeam-channel = "0.5"
dbus = "0.9.5"
fastrand = "1.7.0"
futures = { version = "0.3", features = ["thread-pool"] }
libc = "0.2.125"
log = "0.4"
mio = { version = "0.8.3", features = ["os-ext", "os-poll"] }
nix = "0.24.1"
oci-spec = { git = "https://github.com/containers/oci-spec-rs", rev = "6df620e", features = ["runtime"] }
path-clean = "0.1.0"
procfs = "0.12.0"
prctl = "1.0.0"
libcgroups = { version = "0.0.3", path = "../libcgroups" }
libseccomp = { version = "0.2.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syscalls = "0.5.0"
rust-criu = { git = "https://github.com/checkpoint-restore/rust-criu", version = "0.1.0" }
wasmer = { version = "2.2.0", optional = true }
wasmer-wasi = { version = "2.2.0", optional = true }

[dev-dependencies]
oci-spec = { git = "https://github.com/containers/oci-spec-rs", rev = "6df620e", features = ["proptests", "runtime"] }
quickcheck = "1"
serial_test = "0.6.0"
rand = "0.8.5"
