[package]
name = "libcgroups"
version = "0.0.3"
description = "Library for cgroup"
license-file = "../../LICENSE"
repository = "https://github.com/containers/youki"
homepage = "https://containers.github.io/youki"
readme = "README.md"
authors = ["youki team"]
edition = "2021"
rust-version = "1.58.1"
autoexamples = false
keywords = ["youki", "container", "cgroups"]

[features]
default = ["v1", "v2", "systemd"]
v1 = []
v2 = []
systemd = ["v2", "dbus"]
cgroupsv2_devices = ["rbpf", "libbpf-sys", "errno", "libc"]

[dependencies]
nix = "0.25.0"
procfs = "0.14.1"
log = "0.4"
anyhow = "1.0"
oci-spec = { version = "0.5.8", features = ["runtime"] }
dbus = { version = "0.9.6", optional = true }
fixedbitset = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
rbpf = {version = "0.1.0", optional = true }
libbpf-sys = { version = "0.8.3+v0.7.0", optional = true }
errno = { version = "0.2.8", optional = true }
libc = { version = "0.2.127", optional = true }

[dev-dependencies]
oci-spec = { version = "0.5.8", features = ["proptests", "runtime"] }
quickcheck = "1"
mockall = { version = "0.11.2", features = [] }
clap = "4.0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.9"
serial_test = "0.9.0"
