[package]
name = "libcgroups"
version = "0.1.0"
edition = "2018"
autoexamples = false

[features]
default = ["systemd_cgroups"]
systemd_cgroups = ["systemd"]
cgroupsv2_devices = ["rbpf", "libbpf-sys", "errno", "libc"]

[dependencies]
nix = "0.23.0"
procfs = "0.11.0"
log = "0.4"
anyhow = "1.0"
oci-spec = { git = "https://github.com/containers/oci-spec-rs",  rev = "d6fb1e91742313cd0d0085937e2d6df5d4669720" }
systemd = { version = "0.9", default-features = false, optional = true }
dbus = "0.9.5"
serde = { version = "1.0", features = ["derive"] }
rbpf = {version = "0.1.0", optional = true }
libbpf-sys = { version = "0.5.0-2", optional = true }
errno = { version = "0.2.8", optional = true }
libc = { version = "0.2.106", optional = true }

[dev-dependencies]
oci-spec = { git = "https://github.com/containers/oci-spec-rs",  rev = "d6fb1e91742313cd0d0085937e2d6df5d4669720", features = ["proptests"] }
quickcheck = "1"
clap = "3.0.0-beta.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.9"
