[build]
default-target = "x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-gnu]
dockerfile = "cross/Dockerfile.gnu"

[target.x86_64-unknown-linux-gnu]
dockerfile = "cross/Dockerfile.gnu"

[target.aarch64-unknown-linux-musl]
dockerfile = "cross/Dockerfile.musl"

[target.x86_64-unknown-linux-musl]
dockerfile = "cross/Dockerfile.musl"
