name: Test for podman

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  podman-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: sudo ./.github/scripts/dependency.sh
      - run: make youki-dev
      - run: sudo cp youki /usr/local/bin
      - name: Install requirements for Podman
        run: sudo apt-get install -y pkg-config libsystemd-dev libdbus-glib-1-dev libelf-dev libseccomp-dev libgpgme-dev bats
      - name: Clone podman repository
        uses: actions/checkout@v3
        with:
          repository: containers/podman
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Build podman
        run: make binaries 
      - name: Install tools
        run: make install.tools
      - name: Run podman test
        run: sudo OCI_RUNTIME=/usr/local/bin/youki ./hack/bats 2>&1 | tee build.log 
      - name: Adding Summary
        run: |
          echo "Total tests: 360 Failed tests: $(cat build.log | grep " ok " | wc -l)" >> $GITHUB_STEP_SUMMARY
